---
- name: Include OS-Specific variables
  include_vars: "Debian.yml"

- include_tasks: setup-vars.yml

- name: Ensure apparmor package is installed.
  package: name={{ apparmor_utils_package }} state=present
  register: apparmor_package_install

- name: Ensure ClamAV packages are installed.
  package: name={{ item }} state=present
  with_items: "{{ clamav_packages }}"
  register: clamav_packages_install

- name: Run freshclam after ClamAV packages change.
  command: freshclam
  when: clamav_packages_install.changed
  register: freshclam_result
  notify: restart clamav daemon
  # On Debian, freshclam is automatically run post-install, so this may fail.
  failed_when:
    - freshclam_result.rc != 0
    - freshclam_result.stderr.find('locked by another process') != -1
  tags: ['skip_ansible_lint']

- name: Run aa-complain after ClamAV packages change.
  command: aa-complain clamd
  when: 
    - clamav_packages_install.changed
    - apparmor_package_install.changed
  notify: restart clamav daemon

- name: Change configuration for the ClamAV daemon 1.
  lineinfile:
    path: "{{ clamav_daemon_config_path }}"
    regexp: '{{ item.regexp }}'
    line: "{{ item.line | default('') }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ clamav_daemon_configuration_changes }}"

- name: Change configuration for the ClamAV daemon 2.
  lineinfile:
    path: "{{ clamav_daemon_config_path }}"
    regexp: '{{ item.regexp }}'
    line: "{{ item.line | default('') }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ clamav_daemon_configuration_OnAccessIncludePath }}"

- name: Ensure ClamAV daemon is running (if configured).
  service:
    name: "{{ clamav_daemon }}"
    state: "{{ clamav_daemon_state }}"
    enabled: "{{ clamav_daemon_enabled }}"

- name: Create cronscan script.
  template:
    src: etc/cron/clamav-scan.j2
    dest: /etc/cron.daily/clamav-scan
    owner: root
    group: root
    mode: 0755

- name: Create logrotate clamav file.
  template:
    src: etc/logrotate/clamav.j2
    dest: /etc/logrotate.d/clamav
    owner: root
    group: root
    mode: 0644

- name: Ensure ClamAV freshclam daemon is NOT running (if configured).
  service:
    name: "{{ clamav_freshclam_daemon }}"
    state: "{{ clamav_freshclam_daemon_state }}"
    enabled: "{{ clamav_freshclam_daemon_enabled }}"
  notify: reboot the machine